[WIP] XSD Schema to LutaML classes
lutaml/lutaml-model pull request #184
Opened 2024-11-21 16:14 UTC by suleman-uzair

This PR adds support to generate `Lutaml::Model::Serializable` classes from the provided schema.

closes #37

2025-01-05 09:59 UTC, ronaldtse requested changes
@suleman-uzair can you please help add document to the README so we know how to use it? Thanks.

2025-01-06 15:03 UTC, suleman-uzair commented
@ronaldtse, Updated the **README**. Let me know if anything else is needed.

2025-01-12 10:39 UTC, ronaldtse commented
I'm rebasing and reviewing this now.

2025-01-13 14:34 UTC, ronaldtse commented
As I mentioned in the README, we need to allow direct interpretation of the generated Lutaml::Model classes so the user can directly parse and generate XML. That would be the next task.

2025-01-13 14:34 UTC, ronaldtse approved these changes
Thank you @suleman-uzair !

2025-01-13 14:34 UTC, merged